### ISSUE TITLE
Results of blending are different in browser vs in editor

### ISSUE THREAD

**Issue by tshadowknight** [effekseer/EffekseerForWebGL#112]
I've been trying some blend mode tricks recently and have run into the issue that they tend to not render the same way in the browser compared to in the editor.

A recent example:

![image](https://github.com/user-attachments/assets/d3f2f0ad-7167-442d-8335-cd1d9f8162e9)

VS.

![image](https://github.com/user-attachments/assets/d0cb685a-db1f-48f1-99f0-adeace34f1e7)

The swirls in particular are of note here. They are rendered in front of the core beam but the additive layers of the beam "overcome" the swirls in the editor but not in the browser.

I did some poking around and I suspect this is because the blend operations in webgl are using int and are clamped to 0-255 after each step and that this is likely not the case in the editor. 

I don't know a whole lot about webgl's internal workings so I am wondering if this would be fixable at all?

**Comment by durswd** [comment]
Do you use EmissivePower?

**Comment by tshadowknight** [comment]
The initial example was with Emissive Scaling set to 1, but there are two additive layers of white in the beam.

I tried setting Emissive Scaling to 20 on one of the beam layers as a test and it behaves similarly inconsistent:

In the editor:

![image](https://github.com/user-attachments/assets/bd8fc79a-2c07-4077-abe6-97190637edbe)

In the browser:

![image](https://github.com/user-attachments/assets/80a4a4e4-10de-42af-af72-28c27d44f0d6)

How is emissive scaling implemented? Does it use RGB values greater than 255(or 1)? It could also be getting clamped during blending.

**Comment by durswd** [comment]
WebGL doesn't support HDR(greater than 255)

**Comment by durswd** [comment]
Do you use subtraction or multiply? The render results are different if you render with subtraction after addition

**Comment by tshadowknight** [comment]
Ah, so it's a known limitation. Unfortunate.

There's only additive and blend in these examples.
Tho I have noticed similar behavior with subtract before, I assume it also can't go below 0.

From the bit of research I've done rendering to a float buffer might get around this and I might take a stab at getting that to work. 
I have no idea how well the current code base will deal with that though.
And I'll also have to learn gl while I try, haha.

**Comment by tshadowknight** [comment]
Looks like I'm in luck, webgl somewhat recently added a feature that does exactly what I need.

Setting these:

`gl.getExtension("EXT_color_buffer_float");
gl.getExtension("EXT_color_buffer_half_float");
gl.drawingBufferStorage(gl.RGBA16F, gl.width, gl.height);`

Enables a half float framebuffer, enabling values to go outside the 0-255 range.

I still have an issue with the FXAA I'm using not playing nice with it, but that's not an Effekseer issue.

**Comment by tshadowknight** [comment]
Small Addendum.

When working with Babylon JS setting up the post processing pipeline so that the first buffer is set up as (half) float also achieves this result.

```
const passProcess = new BABYLON.PassPostProcess("Scene copy",
	1.0,
	_camera,
	0,
	scene.getEngine(),
	false,
	BABYLON.Engine.TEXTURETYPE_FLOAT
);
```
