### ISSUE TITLE
effekseer is not restoring state of GL context completely

### ISSUE THREAD

**Issue by manthrax** [effekseer/EffekseerForWebGL#13]
After i spawn my first effekseer effect.. one of my scene textures gets overridden. looks like some webgl context state, like texture binding or something might be getting broken.. or a texture handle is getting overwritten.

**Comment by durswd** [comment]
I will check it

**Comment by durswd** [comment]
I implemented restoring state of GL context

please try it

https://github.com/effekseer/EffekseerForWebGL/releases/download/NightlyBuild/EffekseerForWebGL20191201.zip

APIs are changed a bit from 1.4 if you use wasm veriosn.

**Comment by durswd** [comment]
https://github.com/effekseer/EffekseerForWebGL/releases/download/NightlyBuild/EffekseerForWebGL20191201b.zip

new link

**Comment by manthrax** [comment]
effekseer.min.js:55 Uncaught TypeError: Cannot read property 'registerContext' of undefined
    at EffekseerContext.init (effekseer.min.js:55)
    at Effekseer.init (effekseer.min.js:83)

**Comment by manthrax** [comment]
#20

**Comment by durswd** [comment]
Replied in this issue.

**Comment by manthrax** [comment]
I've taken another shot at it and gotten the 1.6e version working. Closing this. Thank you!
