### ISSUE TITLE
EffekseerForWebGL adds a green wireframe disc at the origin of the effect

### ISSUE THREAD

**Issue by manthrax** [effekseer/EffekseerForWebGL#18]
![image](https://user-images.githubusercontent.com/350247/71971188-ef815800-31be-11ea-9560-16afca454e86.png)

**Comment by manthrax** [comment]
Also note the lack of filtering on the text.. that is the result of issue #13

**Comment by durswd** [comment]
It seem that opengl context is not changed from line to polygon.
I will check it

**Comment by manthrax** [comment]
The disc shouldn't be there at all. It's not a part of the particle system as far as I know?

**Comment by durswd** [comment]
I seem that it is not a particle system.

Please try with new package
https://github.com/effekseer/EffekseerForWebGL/releases/download/NightlyBuild/EffekseerForWebGL150Beta5.zip

**Comment by manthrax** [comment]
This was my error. Apologies. My audio library was adding an audiolistener.
