### ISSUE TITLE
Can't initialize library in 150 beta

### ISSUE THREAD

**Issue by manthrax** [effekseer/EffekseerForWebGL#20]
Uncaught TypeError: Cannot read property 'registerContext' of undefined
    at EffekseerContext.init (effekseer.min.js:59)
    at Effekseer.init (effekseer.min.js:87)
    at new FXLib (FXLib.js:67)

I used to initialize library like this:

    var fxr = new effekseer.constructor(app.renderer.getContext())
    fxr.init(app.renderer.getContext());

Now i've tried:
    effekseer.init(renderer.getContext());
and that fails with the above exception.

**Comment by durswd** [comment]
I will write new sample in this weekend.
Please wait.

**Comment by durswd** [comment]
I updated a package and sample codes.
Please see it.

https://github.com/effekseer/EffekseerForWebGL#how-to-use

**Comment by manthrax** [comment]
I've upgraded to 1.6e and it is working. :) thank you!
