### ISSUE TITLE
Would you please add a clear type specification to the implicit any?

### ISSUE THREAD

**Issue by famibee** [effekseer/EffekseerForWebGL#47]
Would you please add a clear type specification to the implicit any?
　暗黙的な any に明確な型指定を追記して頂けませんか？

thank you for your hard work. Thank you for using this.
It is a request, can you add a clear type specification to implicit any by specifying noImplicitAny: true in compilerOptions of tsconfig.json?
NoImplicitAny is effective in this user project, and about 88 warnings are displayed.

　お疲れ様です。こちら利用させて頂きありがとうございます。
　要望なのですが、tsconfig.json の compilerOptions に noImplicitAny : true の指定で、暗黙的な any に明確な型指定を追記して頂けませんか？
　こちらの使用側プロジェクトで noImplicitAny が有効であり、警告が88個ほど出てしまいます。

I would appreciate it if you could proceed when you have time.

　お時間のあるときに進めて頂ければ幸いです。

**Comment by durswd** [comment]
大分先になるとは思いますが、時間があるときに進めます。
なお、部分的でもPRは大歓迎です。

I'm sure it will be a long time coming, but I'll get to it when I have time.
PR is welcome, even if only partially.

**Comment by famibee** [comment]
ご回答ありがとうございました。よろしくお願いいたします。
どうぞ健やかにお過ごし下さいませ。

Thank you for your answer. Thank you.
Please spend your time in good health.

**Comment by durswd** [comment]
追加しました。
間違い等見つけましたら指摘お願いします。

https://github.com/effekseer/EffekseerForWebGL/blob/master/Release/effekseer.d.ts
