### ISSUE TITLE
Missing Documentation for usage in Three JS

### ISSUE THREAD

**Issue by MossFrog** [effekseer/EffekseerForWebGL#48]
Great software, but there seems to be a lack of documentation on how to use it properly in Three JS. Importing and playing the effekseer effects seems to be easy enough. But how would you update the position of the animation during runtime? How can you dynamically change parameters during runtime such as rotation and scale after the initialization of the effect?

Furthermore is there any way to convert the effects into a regular object3D ? Or even better attach them to an object 3D so that the position rotation and scale values are copied by the effect?

**Comment by MossFrog** [comment]
Okay I seem to have found the member functions which work perfectly after getting a handle of the effekseer effect, but still ill leave the issue open as I have not found a solution to attaching the effect to an object 3D!

**Comment by durswd** [comment]
I added a sample code
https://github.com/effekseer/EffekseerForWebGL/blob/master/Release/Sample/index.html#L34

> any way to convert the effects into a regular object3D 
Nothing

>  the position rotation and scale values
Please set parameters yourself

**Comment by MossFrog** [comment]
Cheers!
