### ISSUE TITLE
Rotation of an effekseer handle

### ISSUE THREAD

**Issue by MossFrog** [effekseer/EffekseerForWebGL#50]
How exactly does setRotation(x,y,z) work? Does the function take Radians as an argument or Degrees? Is the rotation applied to each child node within the effect or just the root node of the effekseer effect? Is this fuction affected by setScale()?

**Comment by durswd** [comment]
I add a value boxes for rotations. 

https://github.com/effekseer/EffekseerForWebGL/commit/5e1218be0acf42c9a2000c20ce4e72fce1abb957

The function takes radians
Root node only

Scale -> Rotation -> Translation
So the function is not affected by setScale

**Comment by MossFrog** [comment]
So how would one copy the rotation of a three JS cube to an effekseer object?

**Comment by durswd** [comment]
Please calculate a matrix by yourself

https://github.com/effekseer/EffekseerForWebGL/blob/master/src/js/effekseer.src.js#L273

**Comment by MossFrog** [comment]
Thank you! PS. The editor on mac-os systems does not export spritesheets properly!

**Comment by durswd** [comment]
I fixed the bug about recording. Please download Effekseer from github actions
