### ISSUE TITLE
Install docs don't mention emcmake

### ISSUE THREAD

**Issue by manthrax** [effekseer/EffekseerForWebGL#52]
$ python build.py
'emcmake' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\work\Effekseer\EffekseerForWebGL\build.py", line 42, in <module>
    compile('build_asmjs',
  File "C:\work\Effekseer\EffekseerForWebGL\build.py", line 15, in compile
    subprocess.check_call(["cmd", "/c", "emcmake", "cmake",
  File "C:\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmd', '/c', 'emcmake', 'cmake', '-G', 'MinGW Makefiles', '-DAS_WASM=OFF', '../src/']' returned non-zero exit status 1.

**Comment by durswd** [comment]
Did you add a PATH for emcmake in an environment variable?

**Comment by manthrax** [comment]
Ideally all the build requirements should be listed in the  How to Develop->Build->Requirements section here:

https://github.com/effekseer/EffekseerForWebGL

By not including all the information, It potentially causes 100s of people to burn time tracking it down.
In a code base meant for public consumption, the docs should have complete information for building from a new dev environment.

**Comment by durswd** [comment]
What you're saying is right.
But emscripten is bothering on Windows.

**Comment by durswd** [comment]
I update the information.
It runs on my environment.
Please tell me if it fails to compile EffekseerForWebGL

**Comment by manthrax** [comment]
I've gotten the 1.6e working and no longer need to recompile so I am closing this. :) Thank you!
