### ISSUE TITLE
EffekseerForWebGL/Release/Sample/index.html doesn't run

### ISSUE THREAD

**Issue by manthrax** [effekseer/EffekseerForWebGL#53]
Effekseer/EffekseerForWebGL/Release/effekseer.js can't be loaded. only effekseer.d.ts

I'd love it if the release contained the working samples etc. out of the box. 

 I think most users would prefer not to manually recompile the library.
 
 <3

**Comment by durswd** [comment]
Please download here.

https://github.com/effekseer/EffekseerForWebGL/releases/download/160d/EffekseerForWebGL160d.zip

You know, it is difficult to compile it.

**Comment by manthrax** [comment]
Thank you!
