### ISSUE TITLE
Can I set current time of the effect ?

### ISSUE THREAD

**Issue by scarletsky** [effekseer/EffekseerForWebGL#76]
Hello, I have a problem about looping the effect.
There are 120 frames in my effect:
0-30 is fade-in
30-90 is loop,
90-120 is fade-out

I want to use `effect.setCurrentTime` to simulate the loop range, is there any way or workaround to do this ?

**Comment by durswd** [comment]
It need to wrap https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/Effekseer/Effekseer/Effekseer.Manager.cpp#L1503

**Comment by scarletsky** [comment]
@durswd OK, I will try to do that. 😄
